import Head from "next/head";
import navbar from "./navbar";

export default function Home() {
  return (
    <div className="font-mono">
      <Head>
        <title>AsZShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {navbar()}
      <main className="bg-primary min-h-full"></main>
    </div>
  );
}
