import Head from "next/head";
import navbar from "./navbar";
import jumbotron from "./jumbotron";

export default function Home() {
  return (
    <div className="font-mono">
      <Head>
        <title>AsZShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {navbar()}
      <main className="bg-primary">
        <div className="min-h-full">
          {jumbotron()}
        </div>
      </main>
    </div>
  );
}
